### ISSUE TITLE
Move Database Connector to outside of handler.

### ISSUE THREAD

**Issue by SimonJTurner** [ricokahler/longtweet.io#1]
https://github.com/ricokahler/longtweet.io/blob/d109d5ee86d3875939c1bafb8bbf9d99f8017f3e/lambdas/list-posts.ts#L16
You could pull the creation of your DynamoDB client object to the outside of the handler. 

This can be helpful because the code inside the handler runs every time the function is invoked, and the code outside only runs on cold starts. So, you could save on creating a new DB client is subsequent calls if they are happening when the function is warm. (A function goes cold in ~300 seconds I think)

_I can fork and make a PR if you like, just don't have the time today_

Here is a relevant post about it from the AWS docs:  [link](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.Lambda.BestPracticesWithDynamoDB.html)

I recommend something along the lines of:
```javascript
var dynamodb = new DynamoDB()
const handler: LambdaHandler = async (event) => {
...
//const dynamodb = new DynamoDB();

 const result = await dynamodb
...

}
```

**Comment by ricokahler** [comment]
This is great! Thanks for the suggestion!
